### ISSUE TITLE
Download via Groundy

### ISSUE THREAD

**Issue by synergeticink** [felipeska/Download-Android#1]
Testing the download via groundy feature, but for some reason the application downloads the file to the data/data..... root directly that requires root access. What do I modify to get it to download the file to the sdcard?

**Comment by felipeska** [comment]
yep replace:

```
File dest = new File(getContext().getFilesDir(), new File(url).getName());
with this:
File dest = new File(Environment .getExternalStorageDirectory(), new File(url).getName());
```
